<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT  (269.99)</name>
   <tag></tag>
   <elementGuidId>ae19762b-4256-40d0-a363-b37818483118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutPopUp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkOutPopUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a72262c5-4f1e-427a-846c-655b9b6c0c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutPopUp</value>
      <webElementGuid>09755d7d-2159-4a52-bafe-17fe1c7bbd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>e878ac26-77f8-4498-8684-f180a0f8a0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2268ef2c-8daa-4671-9804-a9c1a3f8cd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium ng-binding</value>
      <webElementGuid>b8d19dc3-7205-43c2-bc00-3bb0405abb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout($event)</value>
      <webElementGuid>6ba2d8a6-7aa9-4d0b-ad66-4235623c6520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT  ($269.99)</value>
      <webElementGuid>459a1958-b0f5-4b8f-a386-98ddcb0cc00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutPopUp&quot;)</value>
      <webElementGuid>7ec9b153-c72c-4874-a08f-7626daf548a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutPopUp']</value>
      <webElementGuid>f71865fe-ed29-48db-9852-8c12d64bdf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tool-tip-cart[@id='toolTipCart']/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>d4a17a7c-bc17-4b36-a266-fcc6abc533b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>937c361b-0d70-42c9-ada4-00e94815c4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutPopUp' and @name = 'check_out_btn' and (text() = 'CHECKOUT  ($269.99)' or . = 'CHECKOUT  ($269.99)')]</value>
      <webElementGuid>1fbe7e48-18d7-402b-9fd6-e4d4547c1edc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
