<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite 2 - Register Function</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bc87a7e2-c505-484a-b00c-f513f7576727</testSuiteGuid>
   <testCaseLink>
      <guid>177fbc18-cc98-451b-a4ca-19ccc0f1bb9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC 3 - Create acccount with error</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bd38e94c-c9a5-4e7e-8abc-de67e0eab318</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/RegistrationData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bd38e94c-c9a5-4e7e-8abc-de67e0eab318</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>5e0ab2fc-4ce1-4d53-a73a-2b64326c01dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bd38e94c-c9a5-4e7e-8abc-de67e0eab318</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>f3154143-9f92-4d06-bd30-b9c3b4d8b3a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bd38e94c-c9a5-4e7e-8abc-de67e0eab318</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6bec58e5-d107-45f6-995b-0b59b04901b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bd38e94c-c9a5-4e7e-8abc-de67e0eab318</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passwordConfirm</value>
         <variableId>3646d538-74f5-4444-a201-1a43ac0c175a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3986ea49-2c7c-42c8-a309-76f41427aa70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC 4 - Check if confirmation password is equal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16f5ffa3-393a-4d13-8856-cbdfae51f82b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b40fb30-f2ff-4040-93e2-e06ec331f299</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>883b3ba8-5b9e-4f11-bb55-6262d8c15ae3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35e4fc1d-0d18-4946-8527-de7d2346f789</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
