<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>092db01b-b5f4-4b8c-85c4-e4dff68b883b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='helpLink']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#helpLink > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a1315682-2153-4d2f-8085-eb60c9fb7fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../css/images/Down_arrow.svg</value>
      <webElementGuid>05d1db92-a292-4c5d-a5e0-533ff423418b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12px</value>
      <webElementGuid>213a441b-73d4-4e11-aec7-8ec02bbca874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>7px</value>
      <webElementGuid>507114af-156e-4109-a111-29a19145e226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpLink&quot;)/img[1]</value>
      <webElementGuid>675da35a-6903-4769-95f5-1d3593fc32f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='helpLink']/img</value>
      <webElementGuid>0ada4ada-fbf8-4fe5-9c8a-053a2ccb952e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>7aa78faf-9373-4506-a1d8-14b5fce2cb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../css/images/Down_arrow.svg']</value>
      <webElementGuid>0938b790-71fb-4a2e-b836-1c2531f38d6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
