<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_nicehsk</name>
   <tag></tag>
   <elementGuidId>d0cf6518-33e5-4962-8924-486e55d70f0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuUserLink']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.hi-user.containMiniTitle.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>aec5971b-aeb4-4c55-ad40-e6637976dce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>userCookie.response</value>
      <webElementGuid>1f594d7b-fe89-4c71-9a03-47a7607945e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hi-user containMiniTitle ng-binding</value>
      <webElementGuid>efb1690e-2910-4ae5-99a3-9468958a2d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>nicehsk</value>
      <webElementGuid>bacd35c6-794a-4789-8cfa-c8348ef081ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuUserLink&quot;)/span[@class=&quot;hi-user containMiniTitle ng-binding&quot;]</value>
      <webElementGuid>91dfec5b-4c54-4876-a841-56a5f4a3f107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuUserLink']/span</value>
      <webElementGuid>739a56eb-f6c9-4b17-8365-14b65e669268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a/span</value>
      <webElementGuid>a0226c77-a370-4826-82df-5d23564d9f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'nicehsk' or . = 'nicehsk')]</value>
      <webElementGuid>3b103d1e-18ff-4da5-91b1-c5a73421e2fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
