<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Thank you for buying with Advantage</name>
   <tag></tag>
   <elementGuidId>574371e2-9c0c-4572-877d-a607bb3d0674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderPaymentSuccess']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d82e9013-875f-435d-8646-23bd8bcad805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Thank you for buying with Advantage </value>
      <webElementGuid>00e0ef12-3539-4ea7-baba-23c454b4ff76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderPaymentSuccess&quot;)/h2[1]</value>
      <webElementGuid>c2b00f3b-32fa-4567-bf80-9daf83af8a93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']/h2</value>
      <webElementGuid>74185cd9-be64-4432-935b-5d12012a6fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>4fb4c27e-03b2-422e-b80a-d231e652a13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = ' Thank you for buying with Advantage ' or . = ' Thank you for buying with Advantage ')]</value>
      <webElementGuid>c273f11f-477f-4471-8271-562fb865bf04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
