<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Budi Saja</name>
   <tag></tag>
   <elementGuidId>9fed08d9-e569-4c98-9102-54e35dee9270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.innerSeccion > label.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderPaymentSuccess']/div/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>566d5661-b8ea-43cd-aa25-14cd5ae84ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>2544d64c-3fd2-4fae-aae0-8ced2c0f99cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Budi Saja</value>
      <webElementGuid>e4733442-9701-4518-b9d2-3af7c6cd05e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderPaymentSuccess&quot;)/div[1]/div[@class=&quot;seccion borderRight&quot;]/div[1]/div[@class=&quot;innerSeccion&quot;]/label[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>d4d78a4f-3358-4292-a349-76d4bbbfbfdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']/div/div/div/div/label</value>
      <webElementGuid>23401a55-e388-469c-be7a-0f656b0bf256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/label</value>
      <webElementGuid>bb472193-32ef-4877-9cd3-7bc8525894be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Budi Saja' or . = 'Budi Saja')]</value>
      <webElementGuid>8cf17484-d457-4752-89d7-338da23b4c1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
